#=========================================================================#
# doas.conf
#=========================================================================#

#=========================================================================#
# permit user
#=========================================================================#

permit nopass keepenv setenv { PATH } djwilcox


#=========================================================================#
# root as root
#=========================================================================#

permit nopass keepenv setenv { PATH } root as root
