#	$OpenBSD: pf.conf,v 1.55 2017/12/03 20:40:04 sthen Exp $
#
# See pf.conf(5) and /etc/examples/pf.conf

# Macros
tcp_services = "{ 6881, 22000, 8080 }"
udp_services = "{ 6882, 22000, 21027 }"
lan_net      = "192.168.1.0/24"

# Options
set block-policy drop
set skip on lo0

# Normalization & Anti-Spoofing
match in all scrub (no-df)
antispoof quick for egress
block in quick on egress from { no-route, urpf-failed } to any

# Protect package builds (OpenBSD default)
block return out log proto { tcp udp } user _pbuild

# Default rule
block drop all

# Allow all outbound traffic
pass out quick inet

# Inbound rules
pass in on egress proto tcp from $lan_net to egress port ssh
pass in on egress proto tcp to egress port $tcp_services
pass in on egress proto udp to egress port $udp_services
