#	$OpenBSD: pf.conf,v 1.55 2017/12/03 20:40:04 sthen Exp $
#
# See pf.conf(5) and /etc/examples/pf.conf

# Macros
tcp_services = "{ 6881, 22000, 8080 }"
udp_services = "{ 6882, 22000, 21027 }"
lan_net      = "192.168.1.0/24"
ext_if       = "trunk0"

# Options
set block-policy drop
set skip on { lo0 axe0 run0 }

# Normalization & Anti-Spoofing
match in all scrub (no-df)
antispoof quick for $ext_if
block in quick on $ext_if from { no-route, urpf-failed } to any

# Protect package builds (OpenBSD default)
block return out log proto { tcp udp } user _pbuild

# Default rule
block drop all

# Allow all outbound traffic
pass out quick on $ext_if inet keep state

# Inbound rules
pass in on $ext_if proto tcp from $lan_net to ($ext_if) port ssh
pass in on $ext_if proto tcp to ($ext_if) port $tcp_services
pass in on $ext_if proto udp to ($ext_if) port $udp_services
