keyboard.encoding=uk
keyboard.map+="keycode 53 = grave asciitilde plusminus"
keyboard.map+="keycode 50 = section plusminus"
keyboard.map+="keycode 100 = section plusminus"
keyboard.map+="keycode 31 = 2 at twosuperior cent"
keyboard.map+="keycode 52 = apostrophe quotedbl section Agrave"

keyboard1.encoding=uk
keyboard1.map+="keycode 53 = grave asciitilde plusminus"
keyboard1.map+="keycode 50 = section plusminus"
keyboard1.map+="keycode 100 = section plusminus"
keyboard1.map+="keycode 31 = 2 at twosuperior cent"
keyboard1.map+="keycode 52 = apostrophe quotedbl section Agrave"

display.brightness=100%
